Refactor JsonOutput and OpenApiHandler classes to support multiple examples
tomaj/nette-api pull request #143
Opened 2024-04-05 08:39 UTC by Martin-Beranek

Refactor JsonOutput and OpenApiHandler classes to support multiple examples

2024-04-05 09:30 UTC, lulco requested changes
popadala aj pipeline, tak na to mrkni ked to prerobis

2024-04-05 09:30 UTC, lulco commented on src/Output/JsonOutput.php
> +    /** @var array
toto je nejake rozbite

2024-04-05 09:30 UTC, lulco commented on src/Handlers/OpenApiHandler.php
> +                        if (!empty($output->getAdditionalExamples())) {  //Multiple examples processing
nevieme spravit globalne to, ze example v InputParam zmenime na pole a tym padom vzdy a vsade budeme robit s tym jednym fieldom? Maximalne kluc v outpute bude example / examples podla toho ci je tych examplov viac.

metodu setExample by som premenoval na addExample s tym ze by tam myslim malo byt aj meno toho examplu

2024-04-05 10:06 UTC, Martin-Beranek commented on src/Handlers/OpenApiHandler.php
> +                        if (!empty($output->getAdditionalExamples())) {  //Multiple examples processing
Mozem aj tak prerobit ale chcel som spatnu kompatibilitu. Takto ked to niekto updatene nemusi nic menit.

2024-04-05 10:27 UTC, Martin-Beranek commented on src/Handlers/OpenApiHandler.php
> +                        if (!empty($output->getAdditionalExamples())) {  //Multiple examples processing
Pipeline a sniffer by malo prejst. Zmenil som si standard na PSR-2 to je myslim nastavene na code sniffer tu.

2024-04-05 10:50 UTC, lulco commented on src/Handlers/OpenApiHandler.php
> +                        if (!empty($output->getAdditionalExamples())) {  //Multiple examples processing
spatnu kompatibilitu nemusime riesit kedze toto bude 4.0

2024-04-19 18:43 UTC, lulco commented
Vyskúšame, uvidime ;)

2024-04-19 18:44 UTC, merged